"""Summarize existing audit outputs and preserved cases; no model fitting."""
import json,csv,gzip,hashlib
from pathlib import Path
import numpy as np
D=Path(__file__).resolve().parent;H=D.parent/'roster-opportunity'
def read(n):return list(csv.DictReader((D/n).open()))
def save(n,rows):
 with (D/n).open('w',newline='') as f:
  w=csv.DictWriter(f,list(dict.fromkeys(k for a in rows for k in a)));w.writeheader();w.writerows(rows)
r=read('Player_Workload_Decomposition.csv');cs=read('Chronological_Calibration.csv');details=json.loads((D/'Representative_Reconstructions.json').read_text());summary=[]
for rr in ['H','SP','RP']:
 for group,pred in [('all',lambda a:True),('latest_positive',lambda a:float(a['historical_latest_workload'])>0),('latest_zero_or_missing',lambda a:float(a['historical_latest_workload'])==0),('latest_high',lambda a:float(a['historical_latest_workload'])>=(600 if rr=='H' else 150 if rr=='SP' else 50))]:
  xs=[a for a in r if a['role']==rr and pred(a)]
  for k in ['absolute_change','participation_probability','bridge_conditional_model_minus_production','bridge_participation_discount','bridge_replace_or_blend_incumbent']:
   summary.append({'role':rr,'group':group,'n':len(xs),'component':k,'mean':float(np.mean([float(a[k]) for a in xs])) if xs else None,'sum':sum(float(a[k]) for a in xs)})
save('Current_Input_Cohorts.csv',summary)
rolecal=[]
for fam in ['H','P']:
 cases=json.loads(gzip.decompress((H/f'Integrated_{fam}_Cases.json.gz').read_bytes()))
 for rr in ['H'] if fam=='H' else ['SP','RP']:
  xs=[a for a in cases if a['role']==rr and a['anchor']+1!=2020]
  for state in ['absent','part_time','regular'] if fam=='H' else ['absent','RP','SP']:
   def actual(a):
    s=a['actual'];ex=s.get('PA' if fam=='H' else 'IP',0)
    return 'absent' if not ex else ('regular' if ex>=400 else 'part_time') if fam=='H' else 'SP' if s.get('GS',0)>=.5*(s.get('GS',0)+s.get('RA',0)) else 'RP'
   ps=[a['components']['past_only']['probabilities'][state] for a in xs];ys=[int(actual(a)==state) for a in xs]
   rolecal.append({'anchor_role':rr,'future_state':state,'n':len(xs),'predicted':float(np.mean(ps)),'observed':float(np.mean(ys)),'Brier':float(np.mean((np.array(ps)-ys)**2))})
save('Historical_Role_Calibration.csv',rolecal)
# Full branch attribution for the actually selected ensemble, not just incumbent bridge.
branches=[]
for a in r:
 f=lambda k:float(a[k]);rr=a['role'];b=f('production_workload');q=f('participation_probability')
 if rr=='H':
  cr=f('count_raw_appearance_equivalents')*f('appearance_depth');med=f('prior_raw_model_output');weights={'production':b,'raw_branch_level_delta':.5*med+.5*cr-b,'model_output_clipping_delta':.5*(f('prior_clipped_model_output')-med)+.5*f('count_clip_delta')/q if q else .5*(f('prior_clipped_model_output')-med),'participation_delta':.5*f('count_participation_delta'),'branch_role_constraints_delta':.5*f('prior_constraint_delta')+.5*f('count_role_constraint_delta')}
 else:
  cond=f('incumbent_conditional_active_workload');raw=f('prior_raw_model_output');clip=f('prior_clipped_model_output');w=.25 if rr=='SP' else 0
  weights={'production':b,'raw_branch_level_delta':(1-w)*cond+w*raw-b,'model_output_clipping_delta':w*(clip-raw),'participation_delta':(1-w)*(f('incumbent_after_participation')-cond)+w*(f('prior_after_participation_or_direct')-clip),'branch_role_constraints_delta':w*f('prior_constraint_delta')}
 final=f('final_projected_workload');last=final-(b+sum(v for k,v in weights.items() if k!='production'));branches.append({'mlbam_id':a['mlbam_id'],'name':a['name'],'role':rr,**weights,'final_constraint_evidence_delta':last,'final':final,'sum_error':b+sum(v for k,v in weights.items() if k!='production')+last-final})
save('Selected_Branch_Additive_Attribution.csv',branches)
# Extract exact equations source excerpts with numbered lines; frozen input hash manifest supplies provenance.
sourcepaths=[Path('recovered/model/trade-preview-v23/model_v23.py'),D.parent.parent/'opportunity_models.py',D.parent/'shared.py',D.parent/'past_only_followup.py',D.parent/'joint_model.py',D.parent/'hitter_model.py',D.parent/'principal_followup.py',D.parent/'first-year-repair/engine.py',H/'engine.py',H/'hybrid.py',H/'talent.py',H/'integrate.py']
ex=[]
for p in sourcepaths:
 text=p.read_text();ex+=['\n## '+str(p)+'\n','```python\n']+[f'{i:4}: {s}\n' for i,s in enumerate(text.splitlines(),1)]+['```\n']
(D/'Implemented_Source_Trace.md').write_text(''.join(ex))

lines=['# Frozen workload suppression root-cause investigation\n','Diagnostic of research checkpoint `c4d87203ea1cbf14b23a6b6c05cbe56292961740`. No engine changes, training, parameter tuning, or deployment. All 1,900 workload outputs and the production baseline reproduce exactly; additive attribution residual <=5.69e-14. The 3,526 preserved historical cases reconcile exactly. Input/model SHA-256 hashes before/after are unchanged.\n','## Answer and exact population bridge\n','The reduction originates predominantly in the inherited joint opportunity model, before the new blend. The production baseline uses recent positive observed seasons, healthy recovery, and a role prior; the inherited model predicts conditional workloads from all future active seasons (including partial seasons), then weights by any-MLB participation and future role. They are both intended to be unconditional forecasts, but their attrition estimates differ. No second numeric medical discount, roster normalization, or first-year aging multiplication causes this shift.\n','|Group|n|Production|Conditional incumbent|Participation effect|Blend effect|Final|Change|\n|---|---:|---:|---:|---:|---:|---:|---:|\n']
for rr in ['H','SP','RP']:
 xs=[a for a in r if a['role']==rr];mean=lambda k:np.mean([float(a[k]) for a in xs]);lines.append(f"|{rr}|{len(xs)}|{mean('production_workload'):.6f}|{mean('incumbent_conditional_active_workload'):.6f}|{mean('bridge_participation_discount'):.6f}|{mean('bridge_replace_or_blend_incumbent'):.6f}|{mean('final_projected_workload'):.6f}|{mean('absolute_change'):.6f}|\n")
lines+=['\nThe ordered bridge is `(C−production)+(qC−C)+(blend−qC)+(final−blend)`. C is the role-weighted incumbent workload conditional on any MLB activity; it is **not** workload conditional on being healthy all season. These additive differences explain the numerical reduction, not the causal effect of independently removing each predictor. `Selected_Branch_Additive_Attribution.csv` also follows the actually selected blend branches. Counterfactual clipping/calibration columns overlap these bridges and must not be added to them.\n','## Implemented equations and code\n',r'''
Let E_t be PA or decimal IP; IP is outs/3, not base-ten baseball notation. Production in `recovered/model/trade-preview-v23/model_v23.py:75–95`:
- Keep positive same-role seasons 2023–2026. Normalize w=(.1,.2,.3,.4) over kept seasons. R=ΣwE/Σw, H=mean(largest two kept E), L=median preserved calibration role workloads, u=1/(number kept+3).
- W0=min(career cap98%, (1−u)(.7R+.3H)+uL).
- Production W=W0×A(role,rounded export age,rate-quality quartile,year1). `curve:57–73`: A=Σfuture E/Σanchor E over fixed historical cohort; absent future records contribute zero. Low/mid/high states (.25,.5,.25) have mean factor 1. They do not add a second absence discount. H reconciliation preserves PA.

Statistical features (`opportunity_models.py:28–51`, `shared.py:28–55`, `past_only_followup.py:9–20`): latest four calendar exposures, calendar and positive means, max/min/std, zero and positive years, threshold durability run (600PA/150SPIP/50RPIP, schedule-scaled in2020), delta, age, tenure, GP, GS, start share, debut/current verified minor workloads, role changes, career positive years and age×latest. H legacy GP/GS are hardcoded zero; new count features restore GP. P past-only rates use positive same-role recency weights and30IP prior. Age and durability are predictors, not explicit multipliers. Calendar missing rows become E=0 without an observation-status mask. Pre-debut zero lags also exist, though zero_years only counts post-debut.

Participation/role (`shared.py:74–91`): raw HGB classifier probabilities over absent/role1/role2; logistic calibrator acts on log(clipped raw probabilities), fitted on disjoint IDmod5=4 completed seasons. q=1−p_absent. There is no clinical injury survival probability. State labels are zero MLB work, positive part/regular (HPA>=400), or RP/SP (GS/GP>=.5). Core classifier IDsmod5=1,2,3; no target beyond as-of year, max2025. P2020 anchor/target excluded; H2020 annualized162/60 with confidence weight60/162.

Pitch incumbent (`joint_model.py:19–30`, `principal_followup.py:14–27`): for state s, independently fitted squared-error future GS_s and RA_s clipped0..99.5% training count caps. If SP GS<RA or RP GS>RA, set both to their average. Depth dS,dR comes from clipped linear Ridge predictions of pure-role IP/GP. C_s=GS_s dS+RA_s dR. IP=p_RP C_RP+p_SP C_SP. GP=GS+RA; all expected counts use the same probability mixture. Conditional future count labels include interrupted active seasons; no full-health conditional count model exists. The principal follow-up modifies QA3, not IP (`blend=False`).

Prior repair (`first-year-repair/engine.py:52–87`): H absolute-error tree predicts unconditional PA including zero outcomes (median target), clipped0..cap. It receives **no additional q**. P absolute-error active-IP tree predicts a conditional median, clipped0..cap, multiplied by q. RP is bypassed. Cohort `young_entry` precedes `stable_rotation`; Skenes age<=26,tenure<=2 is young_entry. This is a feature classification, not a separate final model router.

New hitter count (`roster-opportunity/engine.py:32–87`): depth d=clip((Σ_{3,2,1}wPA+20×4.1)/(ΣwGP+20),2,5.2), using positive exposure and observed GP. Max recent GP capped162 is a feature. Active tree training label is **future PA/as-of d**, not future GP. Prediction n=clip(tree49features,0,162), preparticipation opportunity C=n d, expected PA=q n d. Active includes partial seasons. Pitch analog d=(ΣwIP+5×5.5)/(ΣwGS+5),clip2.5..7, maxGS capped34; that new P count tree is NOT selected in the final pitching ensemble.

Role reconciliation (`first-year-repair/engine.py:90–117`): H desired=min(cap×q,max(0,total)). Binary search common shift delta over old part and regular forecasts with bounds part[0,400],regular[400,cap]; achievable mean lies in [400p_regular,400p_part+cap p_regular]. It can raise or lower a requested total. This is a constrained representation of an already unconditional total, not automatic q multiplication again. P scales state GS/RA by total/current mixture IP, caps GS36 and RA85−GS, then recomputes state IP with unchanged depths and probabilities. It does not multiply total by q again. Input GS/RA expert fields are metadata; they are not applied as independent counts in this reconciliation.

Blend (`hybrid.py:11–26`): SP=.75 incumbent expected IP+.25 prior-repair expected IP; H=.5 prior-repair expected PA+.5 new-count expected PA; RP=incumbent. Then reconcile once. These have compatible unconditional units, but an absolute-loss median is not an expected mean. Healthy, medical, roster and role components are not fully independently modeled.

Evidence/roster (`engine.py:91–149`, `integrate.py:11–22`): team allocator exists but is never invoked in this replay. No dated team budgets or player allocations exist. The two current factual annotations supply no expected missed appearances or healthy allocations, so numeric effect is zero to floating precision. Generic absence/aging discounts are not added. `expected_appearances` on evidence-annotated pitchers is IP/d, not necessarily final GS+RA; this metadata is not an applied count forecast.

Talent integration (`first-year-repair/engine.py:120–134`, `talent.py`): scale baseline counting stats by new_work/old_work; explicitly assign workload=new_work. Therefore baseline age/attrition factor cancels from the first-year PA/IP. Baseline talent rate aging survives in per-opportunity production; first-year workload is not aged again. QA3 uses the preserved league game definition and bounded conditional yields; SV/HLD remain bounded probability-weighted existing leverage production. Neither changes PA/IP. Existing later seven years and prospect/valuation paths are frozen. The56 conditional value-state clips do not alter exported mean workload.
''' , '\nThe complete numbered implemented functions are preserved in `Implemented_Source_Trace.md`; fitted model bytes and hashes remain unchanged. Histograms/tree predictions have no single coefficient equation; exact frozen artifacts plus the supplied replay are the implemented numerical calculation.\n','## Confirmed causes, defects, and excluded hypotheses\n', '''
1. **Inherited participation/conditional regression is the principal numerical cause.** RP conditional work is actually3.24IP above production, but participation takes away13.05IP. SP conditional work is6.06IP below production and participation subtracts15.70IP. H incumbent conditional work is30.25PA below production and participation subtracts44.86PA. Global probabilities average .63886/.73996/.50243 for H/SP/RP. Many supported assets are not currently full-season incumbents.
2. **Zero/missing latest records are treated as absence evidence without verification.** 190H,40SP,219RP have latest exposure0. All190H also lack latest GP; positive-current H have no missing GP. Pitch GP/GS missing status is falsely reported observed because `observed()` casts fallback feature zeros to floats. Production omits those seasons and renormalizes positive history, while the statistical features include zeros and negative deltas. This divergence is definite; whether each zero is real inactivity is unverified. `Current_Input_Cohorts.csv` quantifies the split. Zero/missing-current mean changes are H−153.91146PA,SP−60.29184IP,RP−19.42610IP versus positive-current H−52.01776PA,SP−14.22955IP,RP−6.10606IP. The zero/missing group accounts for46.34%/42.11%/55.13% of each group's total negative shift, despite only22.59%/14.65%/27.86% of players. High-current usage groups (>=600HPA/150SPIP/50RPIP) change+33.67603PA/−6.91665IP/−1.92990IP. Thus a negative population mean is not uniform downward movement for durable everyday hitters. A source defect cannot be assigned an exact counterfactual cost without the correct historical record; do not label the entire zero-group decline a confirmed data error.
3. **The prior median branch causes specific extreme suppression.** Judge's prior253.07546PA gets50% weight, not the new count454.12297PA alone. Lux/Santander's raw direct median is0.14315PA and role floors lift it to29.74480/12.28480PA; the blend remains75.23174/56.62320PA. The clipping/role floors mostly RAISE hitter forecasts: +1.25575PA average prior constraint,238 affected. Only one new-count role constraint lowers output, −.010617PA population mean (half that in blend). There is no duplicate generic absence multiplier on the direct median.
4. **The architecture has no separate healthy availability or team allocation model.** It separates workload from rate scaling, but active-season statistical count/IP labels already contain partial availability and organizational opportunity. Max recent healthy counts are features/metadata, not a healthy-role allocation. Historical missed work in multiple features/models is not by itself arithmetic double counting. A zero-season forecast conditional on *any* activity legitimately remains smaller than full-health workload. The current implementation cannot identify health versus opportunity causes. Medical annotations provide no causal workload evidence.
5. **Median/mean estimand mismatch is confirmed; its isolated numerical effect is not identified.** Absolute-error branches predict conditional/unconditional medians while export calls the blend expected workload. In skewed workloads, medians can differ materially from means. Raw branch and blending differences are identified, but cannot all be attributed to loss choice because feature/model changes also differ. No retraining was performed to manufacture that attribution.
6. **Calibrator contributes, but is not the dominant population shift.** Holding incumbent conditional predictions fixed, calibrated versus raw probabilities change mean workload by +.28634PA H,−2.50694IP SP,−.41085IP RP. This overlaps the participation bridge. Age/durability are nonlinear model features, not another explicit penalty; their independent effects are not identifiable from the exported point forecast.
7. **Exclusions:** no team allocation penalty; no numeric verified-injury penalty; no duplicated production first-year age factor; no final workload normalization; no new RP blend. Incumbent count/depth clipping adds .01450SPIP/.00441RPIP average. Role count-coherence adjustment has0 numerical effect in this current population. The potentially invalid162 appearance-equivalent cap affects **zero current hitters**, so it is a units defect to repair/test, not the cause of this export. The new blends on average slightly increase the inherited forecast.

2026 provenance: preserved cache is dated2026-10-08, with current seasons from the preserved Fantrax regular-season export. This is a snapshot date, not proof of each row's statistical end date or completeness. No season-level cutoff timestamp exists to distinguish injury-limited full-season records from censored/missing exports. Judge's frozen record is **66GP/285PA**, not a full healthy season; Soto482PA, Pepiot/Berrios/Lux/Santander0. These values are used exactly. They cannot be silently promoted to verified inactivity or replaced with presumed totals. Skenes' record is32GS/174⅓IP. Historic2010–2025 rows are completed annual records; exact original acquisition timestamps are unavailable and explicitly marked unknown in the season CSV.
''' ,'## Historical calibration: evidence supporting some reductions, not blanket acceptance\n','All outcomes are preserved chronological next-season MLB outcomes, not external forecast comparisons. IDmod5=0 holdouts were already exposed; this audit is descriptive and makes no new selection/tuning. Main tables exclude target2020, retaining2020 anchors when permitted for H. Full data contain3526 cases; standard H1215,SP509,RP1685. These expanded populations include prior additional cases, so they differ from the earlier expanded1084P release table. Deciles use as-of historical workload and are equal-rank bins, ties may straddle boundaries. Repeated player-season cases are not independent samples.\n','|Role|n|Observed/predicted participation|Production bias|Hybrid bias|Production MAE|Hybrid MAE|Active hybrid implied bias|\n|---|---:|---|---:|---:|---:|---:|---:|\n']
for a in cs:
 if a['group']=='all':lines.append(f"|{a['role']}|{a['n']}|{float(a['observed_participation']):.4f}/{float(a['predicted_participation']):.4f}|{float(a['production_reference_bias']):.3f}|{float(a['hybrid_bias']):.3f}|{float(a['production_reference_MAE']):.3f}|{float(a['hybrid_MAE']):.3f}|{float(a['hybrid_implied_conditional_active_bias']):.3f}|\n")
lines+=['\nHistorical participation is not uniformly too pessimistic: H predicts71.62% vs70.12% observed; SP67.87% vs70.92%, RP44.80% vs47.42%. Stable rotation is90.54% vs93.69%; young RP61.98% vs70.72%. Thus SP/RP absence calibration contributes modest downward historical bias, especially young RP. Historical baseline overpredicts the aggregate; reducing its aggregate workload is supported. That does not justify every individual reduction. Highest workload deciles have hybrid biases H+7.36PA,SP−2.52IP,RP−2.79IP; stable rotation−7.75IP. The preserved narrower durable_four_years24 gate still fails (94.09MAE versus84.13 strong-prior MAE); broad `durable`33 is a different cohort. Historical selected ensemble retains stable-rotation suppression versus strong prior, while global error improves. Do not reinterpret favorable broad cohorts as passing the predefined failed release gates.\n','\nThe historical “production_reference” is the preserved strict as-of baseline, not a backfilled2026 production curve. Current production uses fixed eight-year cohorts. Historical results therefore establish comparative forecast bias for that saved reference, not that all current2027 differences are warranted. `Historical_Role_Calibration.csv`, `Participation_Reliability.csv`, and chronological case/cohort/year/decile CSVs expose the scoring population and all errors. Conditional active calibration only scores realized active players; final/q is an implied conditional quantity, not an independently healthy fitted estimate.\n','## Twelve player reconstructions\n','Every available input season, role, workload, count, and cutoff is in `Historical_Input_Seasons.csv` and the representative JSON. Injury histories are not available; the current Judge annotation is preserved as provided, not newly verified in this audit. “No evidence” is not “healthy.”\n','|Player|Production|Prior repair|Incumbent active conditional|q|Incumbent expected|New hybrid|Change|\n|---|---:|---:|---:|---:|---:|---:|---:|\n']
for obj in details:
 a=obj['decomposition'];lines.append('|'+a['name']+'|'+ '|'.join(f'{a[k]:.5f}' for k in ['production_workload','previous_repair_workload','incumbent_conditional_active_workload','participation_probability','incumbent_after_participation','final_projected_workload','absolute_change'])+'|\n')
for obj in details:
 a=obj['decomposition'];c=obj['incumbent'];s=obj['previous_repair'];lines.append('\n### '+a['name']+'\n')
 lines.append('Frozen inputs: '+ '; '.join(f"{h['season']}: PA={h['PA']}, IP={h['IP']}, GP={h['GP']}, GS={h['GS']}" for h in obj['historical_inputs'] if h['season']>=2022)+'. See JSON/season CSV for earlier seasons and explicit cutoff limitations.\n')
 lines.append('Role probabilities: '+json.dumps(c['probabilities'])+'. Cohort '+a['cohort']+'. Max recent observed appearances '+str(a['demonstrated_max_appearances'])+'; this does not become an allocated future count.\n')
 if a['role']=='H':
  lines.append(f"New count branch: {a['count_raw_appearance_equivalents']:.10f}×{a['appearance_depth']:.10f}={a['count_before_participation']:.10f} conditional PA; ×q={a['count_after_participation']:.10f}; role reconciliation={a['count_after_role_reconciliation']:.10f}. Prior raw unconditional median={a['prior_raw_model_output']:.10f}; clipped={a['prior_clipped_model_output']:.10f}; reconciled={a['previous_repair_workload']:.10f}. .5 prior+.5 new={a['workload_after_ensemble_blending']:.10f}; final={a['final_projected_workload']:.10f}.\n")
 else:
  lines.append('Incumbent conditional states: '+json.dumps(c['conditional'])+'.\n')
  lines.append(f"Role-weighted active conditional IP={a['incumbent_conditional_active_workload']:.10f}; ×q={a['incumbent_after_participation']:.10f}. Prior active median={a['prior_raw_model_output']:.10f}; ×q={a['prior_after_participation_or_direct']:.10f}; reconciled={a['previous_repair_workload']:.10f}. .75 incumbent+.25 prior={a['workload_after_ensemble_blending']:.10f}; final={a['final_projected_workload']:.10f}.\n")
 keys=['bridge_conditional_model_minus_production','bridge_participation_discount','bridge_replace_or_blend_incumbent'];big=min(keys,key=lambda k:a[k]);lines.append('Largest negative ordered bridge: '+big+f" ({a[big]:.5f}). Injury, roster, additional aging, and final exposure scaling have0 numeric workload effect.\n")
 if a['name']=='Paul Skenes':lines.append('32 observed2026 starts do not enter as a32-start baseline. The inherited model regresses next-season conditional state counts from active seasons including interruptions; conditional SP starts are '+f"{c['conditional']['2']['GS']:.5f}"+'. Its138.68769 active mixture is26.62895IP below production before absence. Absence removes5.82887; the lower prior118.07228 conditional/113.10986 expected gets25% weight and removes another4.93724IP. Final127.92158. Depth5.86392IP/start is not the source of suppression; it exceeds the latest174⅓/32=5.44792. The failed count-capacity response is the actionable mechanism. Historical young-starter aggregate calibration does not establish this individual shortfall as justified; likely player-level count calibration failure, absent a verified expected interruption.\n')
 elif a['name']=='Aaron Judge':lines.append('The model sees285PA/66GP in2026 after704PA/158GP and679PA/152GP, hence `interrupted`. Prior direct median253.07546 receives50% weight; new count454.12297 receives50%. This is exactly353.59922. Compared with using new count alone, that inherited median lowers the final by100.52375PA. The q=.83420 discount removes90.25653 from the new branch before halving its weight. Verified-current-injury metadata has zero numerical penalty and no2027 timetable. No evidence establishes16.58% no-MLB probability or253PA median for this particular durable incumbent; the large decline is a conditional/participation calibration concern amplified by the median blend, not independently verified2027 availability.\n')
 elif a['historical_latest_workload']==0:lines.append('The latest zero/missing row drives interrupted/availability features while production excludes it. The source does not verify whether this is full-season absence or missing/censored data. This result is therefore not defensible as a medical forecast until observation completeness is established; it combines an unresolved input-status defect with statistical regression.\n')
 elif a['name'] in ['Matt Olson','Jose Ramirez']:lines.append('The hybrid increases workload relative to production. Positive current usage and near-certain participation support a substantial active role; no suppression failure appears in the arithmetic. Exact numerical accuracy still requires future outcomes.\n')
 else:lines.append('Positive usage is observed. Most reduction comes from conditional count/workload regression rather than verified injury or roster competition. Historical cohort bias may support some regression, but supplies no player-specific rationale for this exact workload. Treat unusually low counts as a calibration concern, not a confirmed health projection.\n')
lines+=['\n## Minimal corrections proposed for later authorization — not implemented\n', '''
- Add observation-status/completeness fields at input ingestion and preserve unknown GP/GS as unknown. Do not convert missing current exports into inactivity or durable-run breaks; require dated coverage before asserting a missed season. Recover correct dated records before rerunning projections. Keep real zero outcomes in historical labels.
- Correct audit metadata to distinguish appearance equivalents, actual GS/RA, conditional any-active work, and full-health allocated opportunity. Remove the claim that a clinical availability or team allocation layer currently exists. In particular `unconditional_start_expert` and evidence IP/depth counts must not be presented as applied GS/GP.
- Keep unconditional quantities aligned to the desired mean forecast. Evaluate frozen mean candidates against the prior median branch under a newly reserved chronological evaluation plan; do not retune the exposed holdouts. Judge's100.52PA median-blend penalty and stable-rotation cohort underbias are specific tests. No universal floor or external forecast substitution is justified here.
- Repair the hitter equivalent-count cap's dimensional mismatch: bind forecastPA coherently or use actual future GP labels where covered. It has0 current effect, so this correction alone will not solve the present decline.
- For Skenes and comparable established/young32-start pitchers, audit local fitted count response and distinguish partial-active count distribution from roster-informed full-health rotation opportunity. Any replacement must be justified on untouched cohorts and preserve availability exactly once. A validated opportunity estimate should replace the first-year unconditional workload directly, preserving rate and dynasty paths.
- Evaluate participation reliability by incumbent/returning/young/role cohorts before changing probabilities. The aggregate SP/RP calibration gap is real; H overall participation is slightly optimistic, so increasing everybody's participation is contradicted by evidence.
- Keep predefined failed gates binding. A deployment remains blocked pending verified input completeness, full opportunity semantics, stable/durable safeguards and fresh chronological validation. No production changes were made.

Not identified from existing data: exact isolated age/durability predictor effect, clinical missed-time probability, every2026 record's true cutoff, and pure loss-function effect holding all other training choices constant. The report states these limits rather than inventing additive causal costs. No current external PA/IP forecasts enter the model or scoring. The saved annual source comparison/failed external timing gate remains unchanged. An inherited `joint-opportunity/past-hitter-2019.joblib` is0bytes: that fitted checkpoint cannot be loaded. Historical2019 hitter scoring uses preserved cached incumbent components; its full underlying fitted prediction cannot be independently replayed from that empty file. This is a confirmed historical artifact defect, not a source of the current2027 decline. The current fitted models replay successfully; no model was regenerated to conceal the missing artifact.
''']
(D/'Root_Cause_Report.md').write_text(''.join(lines))
save('Representative_Workload_Decomposition.csv',[a for a in r if any(str(x['decomposition']['mlbam_id'])==a['mlbam_id'] for x in details)])
(D/'README.md').write_text('Run from repository recovery root:\n\n```bash\nPYTHONDONTWRITEBYTECODE=1 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 "$CODEX_PRIMARY_RUNTIME_PYTHON" pipeline/docs/model-audit/workload-correction/architecture-investigation/joint-opportunity/workload-root-cause/audit.py recovered/model recovered/beta-unpacked.json\n"$CODEX_PRIMARY_RUNTIME_PYTHON" pipeline/docs/model-audit/workload-correction/architecture-investigation/joint-opportunity/workload-root-cause/summarize.py\n```\n\nRequires preserved checkpoint data/models and compatible Python/scikit-learn. No fit method is invoked. Reports reproduce the frozen export; they do not modify forecast artifacts. Full numbered source trace and SHA256 manifest are included. CSV units are PA or decimal innings. Empty branch values are genuinely not applicable, never filled as fabricated zeros.\n')
print('SUMMARY COMPLETE')
