import {pitchIqLink} from './pitchiq.js';
import {loadAfl,aflCard} from './afl.js';
import {loadProfileHistory,transactionHistory,activateProfileTabs,acquisitionContext} from './profile-history.js';
import {prospectMetrics,prospectSavantLink} from './profile-context.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rank=n=>n==null?'—':`#${n}`;
const cache=new Map();
const nav=()=>'<nav class="editionnav" aria-label="Amateur publication"><a href="#draft">2026 Draft class</a><a href="#international">2027 International</a><a href="#dsl">2026 DSL rankings</a><a href="#international-professionals">International Professionals</a><a href="#october">October Pipeline</a></nav>';
const money=n=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const sourceList=sources=>sources.map(s=>`<div class="source-entry"><h3>${esc(s.name)}</h3><p class="muted">${esc(s.date??'Original publication date unavailable')} · ${esc(s.context)}</p>${s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer"><u>Open source ↗</u></a>`:''}</div>`).join('');
function method(app,data,kind){app.innerHTML=`${nav()}<article class="report"><span class="eyebrow">${kind==='draft'?'DRAFT':'INTERNATIONAL'} / EDITORIAL METHOD</span><h1>Evidence before expectations.</h1><p>${esc(data.methodology)}</p><h2>Source context</h2>${sourceList(data.sources)}<p><a class="button" href="#${kind}">Return to the rankings →</a></p></article>`;}
function profile(app,data,kind,id){
 const p=data.players.find(p=>p.id===id);if(!p){app.innerHTML=`${nav()}<h1>Profile not found</h1><a href="#${kind}">Return to the class →</a>`;return;}
 const intl=kind==='international';
 const facts=intl?[['CLASS','2027 J15'],['PIPELINE RANK',rank(p.pipelineRank)],['EXPECTED ORGANIZATION',p.expectedOrganization],['OFFICIAL ORGANIZATION','Not signed']]:[['PIPELINE CLASS RANK',rank(p.pipelineRank)],['PUBLIC-INPUT CONSENSUS',rank(p.consensusRank)],['AGE / OCT 6',p.age],['MLB DRAFT PICK',`#${p.mlbDraftPick} · Round ${p.mlbDraftRound}`],['DRAFT ORGANIZATION',p.draftOrganization],['VERIFIED BONUS',money(p.signingBonus)]];
 const src=intl?'<p>No numerical publication rank is asserted for this amateur watch list.</p>':Object.entries({ 'DD domestic class order':p.sourceRanks.ddClass,'DD overall prospects':p.sourceRanks.ddOverall,'BA FYPD input':p.sourceRanks.baFypd,'Earlier DD pre-draft input':p.sourceRanks.ddPreDraft,'MLB pre-draft rank':p.sourceRanks.mlbDraft}).filter(([,v])=>v!=null).map(([k,v])=>`<p>${esc(k)} <b>${rank(v)}</b></p>`).join('');
 app.innerHTML=`${nav()}<a href="#${kind}">← ${esc(data.title)}</a><span class="eyebrow amateur-eyebrow">${intl?'INTERNATIONAL AMATEUR / EXPECTED AGREEMENT':'2026 MLB DRAFT / CLASS PROFILE'}</span><h1>${esc(p.name)}</h1><p class="muted">${esc(p.position)} · ${intl?`Expected ${esc(p.expectedOrganization)} · Not officially signed`:esc(p.draftTeamName)} · ${esc(p.playerType)}</p>${intl?'<div class="notice"><b>Expected agreement — not official.</b> Signing destinations can change. No professional statistics or firm ETA are assigned.</div>':''}<div class="profile"><div class="panel"><div class="facts">${facts.map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('')}</div><h2>Scouting context & projection</h2>${p.scoutingParagraphs.map(s=>`<p>${esc(s)}</p>`).join('')}<p class="muted">${esc(p.profileContext)}</p>${intl&&p.research?`<h3>Research check · ${esc(p.research.asOf)}</h3><p><b>${esc(p.research.coverage)}</b></p><p>${esc(p.research.verifiedContext)}</p><p class="muted">${esc(p.research.limitations)}</p>`:''}${acquisitionContext(p)}<h3>Ranking context</h3><p>${intl?esc(p.tier):'Class rank is separate from the owned-prospect October Top 100. The initial Pipeline order uses the public-input model; professional evidence is displayed without automatic small-sample promotions.'}</p><p class="muted">Actual league FYPD selection: not recorded in this edition.</p></div><aside class="panel"><h2>Source ranking inputs</h2>${src}<p><a href="#${kind}-method"><u>Dates, scope and ranking method →</u></a></p><h3>${intl?'Signing context':'Verified draft record'}</h3>${intl?`<p>Expected organization: <b>${esc(p.expectedOrganization)}</b><br>Official organization: <b>Not signed</b></p>${p.reportedBonusExpectation?`<p>Reported bonus expectation: ${esc(p.reportedBonusExpectation)}</p><p class="muted">Reported expectation; see the dated research check and sources. Not a confirmed signing bonus.</p>`:''}`:`<p>${esc(p.school)}<br>${esc(p.bats)} / ${esc(p.throws)} · ${esc(p.height)} · ${esc(p.weight)} lb<br>${esc(p.level??'No verified 2026 pro level')}</p><a href="${esc(p.sourceUrl)}" target="_blank" rel="noopener noreferrer"><u>Official MLB draft data ↗</u></a><p><a href="https://www.milb.com/player/${p.mlbamId}" target="_blank" rel="noopener noreferrer"><u>Official player record ↗</u></a></p>`}<h3>Scouting grades</h3><p class="muted">No numerical tool grades are assigned without a verified report and source date.</p>${prospectSavantLink(p)}${pitchIqLink(p)}${aflCard(p)}</aside></div>${transactionHistory(p)}${!intl?prospectMetrics(p):''}<details class="panel amateur-sources"><summary>Profile sources and limitations</summary>${sourceList(data.sources.filter(s=>p.sourceIds.includes(s.id)))}</details>`;
 activateProfileTabs(app);
}
function listing(app,data,kind){
 const intl=kind==='international';const clubs=[...new Set(data.players.map(p=>intl?p.expectedOrganization:p.draftOrganization))].sort();
 app.innerHTML=`${nav()}<span class="eyebrow">${intl?'THE NEXT INTERNATIONAL CLASS':'THE NEXT GENERATION / DOMESTIC DRAFT'}</span><h1>${intl?'2027 International':'2026 Draft rankings'}</h1><p class="muted">${intl?'Eleven researched J15 candidates · Provisional amateur evaluations':'112 researched draft selections · Neutral public-input class rankings'} · Updated ${esc(data.asOf)}</p><div class="notice">${intl?'<b>Expected agreements, not official signings.</b> This ranks the researched pool, rather than claiming complete global coverage.':'<b>A class ranking with distinct source context.</b> Current Pipeline and computed consensus ranks start from a DD-led public-input baseline. Two players lack ranking inputs and remain unranked.'} <a href="#${kind}-method"><u>Sources and methodology →</u></a></div><div class="controls"><input id="am-search" aria-label="Search amateur prospects" placeholder="Search players…"><select id="am-type" aria-label="Amateur player type"><option value="">All positions</option><option value="H">Hitters</option><option value="P">Pitchers</option></select><select id="am-org" aria-label="Amateur MLB organization"><option value="">${intl?'All expected destinations':'All draft organizations'}</option>${clubs.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select><select id="am-sort" aria-label="Sort amateur prospects"><option value="rank">Pipeline rank</option><option value="name">Player name</option>${!intl?'<option value="age">Age</option><option value="draft">MLB draft pick</option>':''}</select></div><p id="am-count" class="muted" aria-live="polite"></p><div class="tablewrap"><table><thead><tr><th>PIPELINE</th><th>PROSPECT</th><th>${intl?'EXPECTED ORGANIZATION':'DRAFT ORGANIZATION'}</th><th>${intl?'STATUS':'AGE / LEVEL'}</th><th>${intl?'TIER':'CONSENSUS'}</th><th>${intl?'PROFILE':'DD / BA CLASS INPUT'}</th></tr></thead><tbody id="am-rows"></tbody></table></div><p class="muted">${intl?'No signing destination is official. Amateur projections carry substantial development uncertainty.':'DD class order is derived from the October overall prospect input; BA ranks are imported FYPD context. MLB Draft picks are actual MLB selections, not fantasy draft picks.'}</p>`;
 const render=()=>{const q=document.querySelector('#am-search').value.trim().toLowerCase(),t=document.querySelector('#am-type').value,o=document.querySelector('#am-org').value,sort=document.querySelector('#am-sort').value;let rows=data.players.filter(p=>p.name.toLowerCase().includes(q)&&(!t||p.type===t)&&(!o||(intl?p.expectedOrganization:p.draftOrganization)===o));rows.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='age'?a.age-b.age:sort==='draft'?a.mlbDraftPick-b.mlbDraftPick:(a.pipelineRank??10000)-(b.pipelineRank??10000));document.querySelector('#am-count').textContent=`${rows.length} of ${data.players.length} players shown`;document.querySelector('#am-rows').innerHTML=rows.map(p=>`<tr><td>${rank(p.pipelineRank)}</td><td><a href="#${kind}-player/${p.id}">${esc(p.name)}</a><small>${esc(p.position)} · ${esc(p.playerType)}</small></td><td>${intl?`Expected ${esc(p.expectedOrganization)}`:esc(p.draftOrganization)}</td><td>${intl?'Not officially signed':`${p.age} · ${esc(p.level??'Pro level unavailable')}`}</td><td>${intl?esc(p.tier):rank(p.consensusRank)}</td><td>${intl?`<a href="#international-player/${p.id}">Read report →</a>`:`${rank(p.sourceRanks.ddClass)} / ${rank(p.sourceRanks.baFypd)}`}</td></tr>`).join('')||'<tr><td colspan="6">No prospects match these filters.</td></tr>';};document.querySelector('#am-search').oninput=render;for(const id of ['am-type','am-org','am-sort'])document.querySelector('#'+id).onchange=render;render();
}
export async function showAmateurs(app,page,id){
 const kind=page.startsWith('international')?'international':'draft';const current=location.hash;
 app.innerHTML=`${nav()}<p>Loading ${kind==='draft'?'the draft class':'international prospects'}…</p>`;
 try{if(!cache.has(kind))cache.set(kind,fetch(`data/${kind}/${kind==='draft'?'2026':'2027'}.json`).then(r=>{if(!r.ok)throw Error('Publication unavailable');return r.json();}));const data=await cache.get(kind);if(page.endsWith('-player'))await Promise.all([loadProfileHistory(),loadAfl()]);if(location.hash!==current)return;if(page.endsWith('-method'))method(app,data,kind);else if(page.endsWith('-player'))profile(app,data,kind,id);else listing(app,data,kind);}catch(e){cache.delete(kind);if(location.hash===current)app.innerHTML=`${nav()}<h1>Publication unavailable</h1><p>Refresh to retry loading this class.</p>`;}
}
