import {pitchIqLink} from './pitchiq.js';
import {loadAfl,aflCard,aflResources} from './afl.js';
import {prospectSavantLink} from './profile-context.js';
import {activateHomeSearch} from './home-search.js';
import {loadProfileHistory,transactionHistory,activateProfileTabs,acquisitionContext} from './profile-history.js';
import {showRosters} from './rosters.js';
import {showOctober} from './october.js';
import {showAmateurs} from './amateurs.js';
import {showDsl} from './dsl.js';
import {showProfessionals} from './international-professionals.js';
const app=document.querySelector('#app');
const resources=document.querySelector('.nav-resources');
const headerMenus=[...document.querySelectorAll('header nav details')];
for(const menu of headerMenus){
 menu.addEventListener('toggle',()=>{
  if(menu.open)for(const other of headerMenus)if(other!==menu)other.open=false;
 });
}

resources.addEventListener('click',event=>{
 if(event.target.closest('a'))resources.open=false;
});
document.addEventListener('click',event=>{
 if(!resources.contains(event.target))resources.open=false;
});
document.addEventListener('keydown',event=>{
 if(event.key==='Escape'&&resources.open){resources.open=false;resources.querySelector('summary').focus();}
});
window.addEventListener('hashchange',()=>{resources.open=false;});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let players,orgs,edition,ownership,currentEdition;
const card=o=>`<a class="card" href="#organization/${o.id}"><span class="badge">${o.prototype?'PROTOTYPE AVAILABLE':'IN THE LEAGUE'}</span><h3>${esc(o.name)}</h3><p>${o.prototype?'Explore the August Top 30 archive →':'Organization page · editorial work pending →'}</p></a>`;
function home(){const leader=currentEdition.rankings.find(p=>p.leagueRank===1);app.innerHTML=`<section class="home-search" aria-labelledby="profile-search-label"><form id="profile-search-form" role="search"><label id="profile-search-label" for="profile-search">Find a player profile</label><div class="profile-search-field"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="10.5" cy="10.5" r="6.5"></circle><path d="m16 16 5 5"></path></svg><input id="profile-search" type="search" placeholder="Search by player name…" autocomplete="off" aria-describedby="profile-search-status"><button type="submit">Search <span aria-hidden="true">↗</span></button></div></form><p id="profile-search-status" aria-live="polite"></p><ul id="profile-search-results" hidden></ul></section><section class="hero"><div><span class="eyebrow">THE LEAGUE’S NEXT GENERATION</span><h1>Tomorrow’s stars.<br>Our own Pipeline.</h1><p>A permanent home for BangaLangin’s prospect rankings, scouting reports, and farm systems. Twelve organizations. One independent perspective.</p><a class="button" href="#october">Explore the League Top 100 ↗</a></div><div class="feature"><span class="eyebrow">BANGALANGIN #1 / OCTOBER 2026</span><div class="big">#1</div><h2>${esc(leader.name)}</h2><p>${esc(leader.organization)}<br>${esc(leader.rankingPosition)} · ${esc(leader.mlbOrg)} · League’s top-ranked prospect</p><a href="#october-player/${esc(leader.playerId)}">View prospect profile →</a></div></section><div class="stats"><div><b>12</b><span>FANTASY ORGANIZATIONS</span></div><div><b>01</b><span>ARCHIVED EDITION</span></div><div><b>${currentEdition.rankings.length}</b><span>RANKED PROSPECTS</span></div></div><section><div class="sectionhead"><div><span class="eyebrow">TWELVE FARMS. ONE LEAGUE.</span><h2>Browse the organizations</h2></div><a href="#october-farms">Compare all twelve →</a></div><div class="grid">${orgs.map(o=>`<a class="card" href="#october-org/${o.id}"><span class="badge">OCTOBER 2026</span><h3>${esc(o.currentName??o.name)}</h3><p>Explore the organizational Pipeline →</p></a>`).join('')}${[['League Top 100','october'],['Farm System Rankings','october-farms']].map(([t,route])=>`<a class="card" href="#${route}"><span class="badge">OCTOBER 2026 WORKING EDITION</span><h3>${t}</h3><p>Browse the league's non-debuted prospects and transparent system rankings →</p></a>`).join('')}</div></section>${aflResources()}<div class="notice">October 2026 working edition · League rankings cover non-debuted prospects. Previous rankings remain preserved in the August archive. Current ownership is available in the October 6 roster snapshot. <a href="#rosters"><b>Browse current rosters →</b></a></div><p class="muted" style="font-size:12px;margin-top:24px">October working rankings · Non-debuted prospects only. <a href="#october-review"><u>Eligibility audit →</u></a></p>`;activateHomeSearch(app,currentEdition,edition,players)}
function organization(id){const o=orgs.find(x=>x.id===id);if(!o)return missing();app.innerHTML=`<a href="#organizations">← All organizations</a><span class="eyebrow" style="display:block;margin-top:30px">BANGALANGIN ORGANIZATION PIPELINE</span><h1>${esc(o.name)}</h1>${o.prototype?`<p class="muted">Top 30 prospects · August 2026 historical edition</p><div class="notice">Historical rankings and ownership are preserved together. The supplied Shea roster is a separate snapshot with no verified export date; it does not rewrite this edition.</div><div class="controls"><input id="search" aria-label="Search prospects" placeholder="Search the Shea Top 30…"><select id="type" aria-label="Player type"><option value="">All prospects</option><option value="H">Hitters</option><option value="P">Pitchers</option></select></div><div class="tablewrap"><table><thead><tr><th>RANK</th><th>PROSPECT</th><th>MLB</th><th>AGE*</th><th>TIER</th><th>LEAGUE</th></tr></thead><tbody id="rows"></tbody></table></div><p class="muted">*Age and MLB organization reflect the source workbook. Level, movement, and statistical metrics are omitted where unavailable.</p>`:`<div class="panel"><h2>The next organization on deck.</h2><p class="muted">Navigation is ready. This organization’s publication page will be completed after the prototype is reviewed and ownership is verified.</p><a class="button" href="#organization/shea-stadiums">Open the working prototype →</a></div>`}`;if(o.prototype){const render=()=>{const q=document.querySelector('#search').value.toLowerCase(),t=document.querySelector('#type').value;const rows=edition.rankings.filter(r=>r.organizationId===id).map(r=>({...r,p:players.find(p=>p.id===r.playerId)})).filter(r=>r.p.name.toLowerCase().includes(q)&&(!t||r.p.type===t));document.querySelector('#rows').innerHTML=rows.map(r=>`<tr><td>${r.organizationRank}</td><td><a href="#player/${r.playerId}">${esc(r.p.name)}</a><small>${esc(r.p.position)} · ETA ${esc(r.p.eta)}</small></td><td>${esc(r.p.mlbOrg)}</td><td>${esc(r.p.age)}</td><td>${esc(r.tier)}</td><td>#${r.leagueRank}</td></tr>`).join('')||'<tr><td colspan="6">No prospects match these filters.</td></tr>'};document.querySelector('#search').oninput=render;document.querySelector('#type').onchange=render;render()}}
async function profile(id){const current=location.hash;await Promise.all([loadProfileHistory(),loadAfl()]);if(location.hash!==current)return;const p=players.find(p=>p.id===id),r=edition.rankings.find(r=>r.playerId===id);if(!p||!r||r.organizationId!=='shea-stadiums')return missing();const roster=ownership.players.find(x=>x.name===p.name);app.innerHTML=`<a href="#organization/shea-stadiums">← Shea Stadiums Top 30</a><span class="eyebrow" style="display:block;margin-top:32px">ARCHIVED PROSPECT PROFILE / AUGUST 2026</span><h1>${esc(p.name)}</h1><p class="muted">${esc(p.position)} · ${esc(p.mlbOrg)} · ${esc(r.tier)}</p><div class="profile"><div class="panel"><div class="facts"><div><span>ORG RANK</span><b>#${r.organizationRank}</b></div><div><span>LEAGUE RANK</span><b>#${r.leagueRank}</b></div><div><span>AGE IN SOURCE</span><b>${p.age}</b></div><div><span>ETA IN SOURCE</span><b>${p.eta}</b></div></div><h2>Ranking context</h2><p>${esc(r.note)}</p><p class="muted">Imported model note, not a new scouting report. Strengths, risks, dynasty outlook, and performance metrics will appear once researched and sourced.</p>${acquisitionContext(p)}<h2>Ranking history</h2><p>August 2026 · Shea Stadiums <b>#${r.organizationRank}</b> · League <b>#${r.leagueRank}</b></p></div><aside class="panel"><span class="eyebrow">SOURCE SNAPSHOT</span><h2>Publication context</h2>${Object.entries(p.sources).filter(([k,v])=>v!==null).map(([k,v])=>`<p>${esc(k)} <b>#${v}</b></p>`).join('')}<p class="muted">These ranks are reported by the imported workbook and have not been independently reverified.</p><h3>Ownership</h3><p>${roster?'Present in supplied Shea roster snapshot.':'Not matched by exact name in supplied Shea roster snapshot; current ownership unresolved.'}</p><p class="muted">Export date unspecified. August ownership remains historical.</p>${prospectSavantLink(currentEdition.rankings.find(row=>row.archivePlayerId===p.id)??p)}${pitchIqLink(currentEdition.rankings.find(row=>row.archivePlayerId===p.id)??p)}${aflCard(currentEdition.rankings.find(row=>row.archivePlayerId===p.id)??p)}</aside></div>${transactionHistory(p)}`;activateProfileTabs(app)}
function methodology(){app.innerHTML=`<article class="report"><span class="eyebrow">EDITORIAL PRINCIPLES</span><h1>The evaluation comes first.</h1><h2>Independent rankings</h2><p>Evaluate dynasty value using scouting, performance, age relative to level, ceiling, probability, and league context. New information changes an evaluation in proportion to its significance. Ownership, personal favorites, hype, and page layout do not determine rankings.</p><h2>The August archive</h2><p>The imported workbook uses a weighted consensus: Dynasty Dugout 50%, Pitcher List 30%, FanGraphs 20%, with exponentially declining rank scores and censored values for unlisted players. It also preserves selected research anchors. This is an archived model, not a freshly researched edition. Its source report is not included in the supplied files, so its calibration cannot be fully audited here.</p><h2>Farm systems: October model</h2><p>The October farm edition measures elite talent, Top-10 quality, usable depth, ceiling, proximity, hitting, pitching, and development risk with visible component formulas. The October edition now publishes model-based system indices and explanations. <a href="#october-farms"><u>Open farm rankings →</u></a> · <a href="#october-farm-method"><u>See component formulas →</u></a></p><h2>Ownership and history</h2><p>Each edition stores its own organization assignments and rankings. Current ownership lives separately and must come from the newest verified league-wide Fantrax export. Trades never rewrite historical editions. Player identifiers persist across editions; missing values stay missing.</p><h2>Source discipline</h2><p>Metrics require a source, sample size, season, and retrieval date. Imported ranking context is labeled separately from original scouting. The supplied Rule 5 document is a proposal and must not be treated as an adopted league rule without verification.</p></article>`}
function roadmap(){app.innerHTML='<article class="report"><span class="eyebrow">DEVELOPMENT ROADMAP</span><h1>A publication built to last.</h1><h2>01 / Foundation</h2><p>Homepage, 12-organization navigation, structured data, and Shea Stadiums prototype. GitHub checkpoints and Vercel deployment are connected.</p><h2>02 / Organizational Pipeline</h2><p>Verify ownership, research and finalize Top 30s, organization summaries, tiers, search, and movement when two comparable editions exist.</p><h2>03 / League database</h2><p>Publish the researched Top 100, farm rankings with documented methodology, full profiles, and league-wide filters.</p><h2>04 / History and comparisons</h2><p>Add edition switching, movement charts, comparisons, and sourced performance integrations.</p></article>'}
function missing(){app.innerHTML='<h1>Page not found</h1><a class="button" href="#home">Return to the Pipeline</a>'}
function updateHeader(page){
 const active=['october-farms','october-farm-method'].includes(page)?'october-farms':page.startsWith('october')?'october':page.startsWith('draft')?'draft':(page.startsWith('international')||page.startsWith('dsl'))?'international':['rosters','organizations','organization','player','methodology'].includes(page)?'resources':'home';
 for(const link of document.querySelectorAll('header nav > a')){
  if(link.hash===`#${active}`)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');
 }
 resources.classList.toggle('is-active',active==='resources');
 const intl=document.querySelector('.nav-international');
 intl.classList.toggle('is-active',active==='international');
 for(const link of intl.querySelectorAll('a')){const selected=link.hash==='#international-professionals'?page==='international-professionals'||page==='international-pro-player':link.hash==='#dsl'?page.startsWith('dsl'):['international','international-player','international-method'].includes(page);if(selected)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');}
 intl.open=false;
}
function route(){const [page,id]=location.hash.slice(1).split('/');document.body.classList.toggle('international-mode',page?.startsWith('international')||page==='dsl');updateHeader(page??'home');if(!page||page==='home')home();else if(page==='organizations')app.innerHTML=`<span class="eyebrow">TWELVE FARMS. ONE LEAGUE.</span><h1>The organizations</h1><div class="grid">${orgs.map(card).join('')}</div>`;else if(['october','october-org','october-player','october-method','october-review','october-farms','october-farm-method'].includes(page))showOctober(app,page,id,orgs,edition);else if(['international-professionals','international-pro-player'].includes(page))showProfessionals(app,page,id);else if(['draft','draft-player','draft-method','international','international-player','international-method'].includes(page))showAmateurs(app,page,id);else if(page==='dsl'||page==='dsl-player')showDsl(app,page,id,players,currentEdition,orgs);else if(page==='rosters')showRosters(app);else if(page==='organization')organization(id);else if(page==='player')profile(id);else if(page==='methodology')methodology();else if(page==='roadmap')roadmap();else missing();window.scrollTo(0,0)}
try{[players,orgs,edition,ownership,currentEdition]=await Promise.all(['players.json','organizations.json','editions/august-2026.json','ownership.json','editions/october-2026.json'].map(async path=>{const r=await fetch(`data/${path}`);if(!r.ok)throw Error('Data unavailable');return r.json()}));window.addEventListener('hashchange',route);route()}catch(e){app.innerHTML='<h1>The Pipeline is unavailable.</h1><p>Refresh to try loading the publication again.</p>'}
