const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rank=n=>n==null?'—':`#${n}`;
const baUrl='https://www.baseballamerica.com/stories/top-35-dominican-summer-league-mlb-prospects-in-2026/';
const seedUrl='https://www.youtube.com/';
const data=[
['Angeibel Gomez','OF','Royals'],['Yostin Peña','OF','Yankees'],['Albert Fermín','SS','Astros'],['Francisco Renteria','OF','Phillies'],['Johenssy Colome','SS','Athletics'],['Ricki Moneys','SS','Brewers'],['Sebastian Rojas','C','Cardinals'],['Leanders Matos','3B','Brewers'],['Joniel Hernandez','SS','Giants'],['Wandy Asigen','SS','Mets'],['Diego Frontado','SS','Brewers'],['Juan Rijo','OF','Angels'],['Jose Luis Acevedo','SS','Angels'],['Jose Manon','SS','Braves'],['Ismael Mena','OF','Padres'],['Victor Valdez','SS','Rays'],['Santiago Solarte','SS','Marlins'],['Kendri Fana','RHP','Angels'],['Jorwin Pulido','C','Braves'],['Jose Rodriguez','SS','Brewers'],['Juan Parra','SS','Phillies'],['Jaider Suárez','SS','Royals'],['Carlos Tejera','OF','Pirates'],['Alexander Mercedes','LHP','Brewers'],['Yordany Marte','RHP','White Sox'],['Breyner Figuereo','LHP','Rangers'],['Manuel Bolivar','C','Tigers'],['Jeremy Suriel','OF','D-backs'],['Luis Ramon King','OF','Royals'],['Joskairo Ramirez','OF','Red Sox'],['Martires Polanco','RHP','Braves'],['Ronny Muñoz','SS','Marlins'],['Dawvris Brito','SS','Red Sox'],['Eduardo Tusen','SS','Tigers'],['Enrique Oropeza','OF','Cubs']
].map((x,i)=>({rank:i+1,name:x[0],position:x[1],organization:x[2]}));
const seed={"Angeibel Gomez":[1,184.5],"Francisco Renteria":[2,158.3],"Yostin Peña":[4,183.3],"Leanders Matos":[5,160.4],"Samil Serrano":[6,164.2],"Diego Frontado":[7,133.9],"Joniel Hernandez":[8,131.7],"Johenssy Colome":[9,127.6],"Albert Fermín":[10,127],"Santiago Solarte":[11,144.8],"Juan Parra":[14,150.5],"Ronald Cardozo":[15,137.2],"Jaider Suárez":[19,115.9],"Helvin Mendoza":[20,112.6],"Sebastian Rojas":[21,84.6],"Juan Torres":[24,90.1],"Diego Fernandez":[25,78.4],"Daniel Pire":[26,144.1],"Yhon Guerrero":[27,122.5]};
const board=data.map(p=>{const s=seed[p.name];return {...p,seedRank:s?.[0]??null,seedScore:s?.[1]??null,compositeScore:s?((p.rank*.6)+(s[0]*.4)):p.rank}}).sort((a,b)=>a.compositeScore-b.compositeScore).map((p,i)=>({...p,compositeRank:i+1}));
export function showDsl(app){app.innerHTML=`<nav class="editionnav" aria-label="International editions"><a href="#draft">2026 Draft class</a><a href="#international">2027 International</a><a href="#dsl" aria-current="page">2026 DSL rankings</a><a href="#october">October Pipeline</a></nav><span class="eyebrow">INTERNATIONAL / DOMINICAN SUMMER LEAGUE</span><h1>2026 DSL rankings</h1><p class="muted">Baseball America’s Top 35 with Seed Stage scouting context · Updated October 6, 2026</p><div class="notice"><b>Read the sources together.</b> BA supplies 60% of the Pipeline composite and Seed Stage scouting supplies 40% when a rank is confirmed in the supplied Aug. 30 video. Players without a confirmed Seed Stage rank retain their BA placement.</div><div class="controls"><input id="dsl-search" aria-label="Search DSL prospects" placeholder="Search players…"><select id="dsl-org"><option value="">All organizations</option>${[...new Set(data.map(p=>p.organization))].sort().map(o=>`<option>${esc(o)}</option>`).join('')}</select></div><p id="dsl-count" class="muted"></p><div class="dsl-grid" id="dsl-grid"></div><article class="report"><h2>Sources and method</h2><p>Baseball America’s September 4, 2026 article supplies 60% of each composite score; Seed Stage’s supplied Aug. 30, 2026 scouting rank supplies 40% where verified. Composite scores are calculated as (BA rank × 0.60) + (Seed Stage rank × 0.40), then ordered ascending. If Seed Stage rank is unavailable, the BA rank carries forward unchanged.</p><p><a class="button" href="${baUrl}" target="_blank" rel="noopener noreferrer">Open Baseball America ↗</a> <a class="button" href="${seedUrl}" target="_blank" rel="noopener noreferrer">Open Seed Stage source ↗</a></p></article>`;const render=()=>{const q=document.querySelector('#dsl-search').value.toLowerCase(),o=document.querySelector('#dsl-org').value;const rows=board.filter(p=>p.name.toLowerCase().includes(q)&&(!o||p.organization===o));document.querySelector('#dsl-count').textContent=`${rows.length} of ${data.length} players shown`;document.querySelector('#dsl-grid').innerHTML=rows.map(p=>{const s=seed[p.name];return `<article class="panel dsl-card"><div class="dsl-rank">${rank(p.compositeRank)}</div><div><h2>${esc(p.name)}</h2><p class="muted">${esc(p.position)} · ${esc(p.organization)}</p><p><b>Pipeline composite:</b> ${rank(p.compositeRank)}<br><b>BA rank (60%):</b> ${rank(p.rank)}<br><b>Seed Stage (40%):</b> ${s?`${rank(s[0])} · ${s[1]} SSS`:'Not captured'}</p><a href="${baUrl}" target="_blank" rel="noopener noreferrer"><u>BA source ↗</u></a></div></article>`}).join('')||'<p>No prospects match these filters.</p>';};document.querySelector('#dsl-search').oninput=render;document.querySelector('#dsl-org').onchange=render;render();}
