const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={elite:'Elite talent',topTen:'Top-ten quality',depth:'Depth',ceiling:'Ceiling',proximity:'Proximity',hitting:'Hitting',pitching:'Pitching',certainty:'Lower risk'};
export function farmPage(edition,nav){
  return `${nav}<span class="eyebrow">OCTOBER 2026 / NON-DEBUTED ONLY</span><h1>Farm System Power Rankings</h1><p class="muted">Twelve organizations. One transparent model. Updated October 6.</p><div class="notice"><b>Pipeline model rankings.</b> The Farm Value Index sets this edition's leader to 100. It is a relative system score, not WAR or a 20–80 scouting grade. MLB-debuted players are excluded. <a href="#october-farm-method"><u>See every component and formula →</u></a></div><div class="tablewrap"><table class="farmtable"><thead><tr><th>FARM RANK</th><th>ORGANIZATION</th><th>FARM VALUE INDEX</th><th>GAP TO LEADER</th><th>FARM TIER</th><th>ELIGIBLE</th></tr></thead><tbody>${edition.farms.map(f=>`<tr><td>${f.rank}</td><td><a href="#october-org/${f.organizationId}">${esc(f.name)}</a></td><td><div class="indexbar"><i style="width:${f.index}%" aria-hidden="true"></i><b>${f.index.toFixed(1)}</b></div></td><td>${f.gap.toFixed(1)}</td><td><span class="farmtier">${esc(f.tier)}</span></td><td>${f.eligibleCount}</td></tr>`).join('')}</tbody></table></div><div class="farmreports">${edition.farms.map(f=>`<article class="panel"><span class="eyebrow">#${f.rank} / ${esc(f.tier)}</span><h2><a href="#october-org/${f.organizationId}">${esc(f.name)}</a></h2><p>${esc(f.explanation)}</p><div class="farmcomponents">${Object.entries(f.components).map(([k,v])=>`<div><span>${labels[k]}</span><b>${v.toFixed(1)}</b></div>`).join('')}</div><p class="muted">Component indices relative to this league. Higher “Lower risk” means more development certainty.</p></article>`).join('')}</div>`;
}
export function farmMethod(edition,nav){
  const m=edition.farmMethodology;
  return `${nav}<article class="report"><span class="eyebrow">FARM RANKINGS / OCTOBER METHOD</span><h1>Talent, depth and a path to MLB.</h1><p>${esc(m.limitations)}</p><h2>Prospect value</h2><p>Each eligible player's league rank maps to a declining value curve. This rewards elite players much more than distant depth pieces. Organizational ranks are never added together.</p><code class="formula">${esc(m.valueCurve)}</code><h2>The eight components</h2>${Object.entries(m.weights).map(([k,w])=>`<h3>${labels[k]} · ${(w*100).toFixed(0)}%</h3><p>${esc(m.components[k])}</p>`).join('')}<h2>Development certainty</h2><p>${esc(m.certaintyFormula)}</p><h2>Ceiling</h2><p>${esc(m.ceilingFormula)}</p><h2>Index and tiers</h2><p>${esc(m.normalization)}</p><p>${esc(m.tiers)}</p><h2>Interpreting change</h2><p>Graduations remove farm value even if the player is succeeding in MLB. New ownership changes the current farm; it never rewrites the August archive. Source omissions, dated tool grades, short samples, and editorial placements introduce uncertainty. These weights are editorial choices and future versions should be compared as separate editions.</p><a class="button" href="#october-farms">Open the farm rankings →</a></article>`;
}
