const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let loaded;
const sourceLabel={dd:'Dynasty Dugout',pl:'Pitcher List',fg:'FanGraphs',jb:'Just Baseball',ba:'Baseball America'};
const movement=p=>p.movement==null?'—':p.movement>0?`↑ ${p.movement}`:p.movement<0?`↓ ${Math.abs(p.movement)}`:'↔';
const link=p=>`#october-player/${p.playerId}`;
export async function showOctober(app,page,id,organizations,archive) {
  app.innerHTML='<p role="status">Loading the October edition…</p>';
  try {
    loaded??=fetch('data/editions/october-2026.json').then(r=>{if(!r.ok)throw Error('Edition unavailable');return r.json()}).catch(e=>{loaded=null;throw e});
    const edition=await loaded;
    // A route may change while the lazy request is in flight.
    const [activePage,activeId]=location.hash.slice(1).split('/');
    if(activePage!==page||activeId!==id)return;
    const orgName=orgId=>{const o=organizations.find(o=>o.id===orgId);return o?.currentName??o?.name??orgId};
    const nav=`<div class="editionnav"><a href="#october">October rankings</a><a href="#october-review">Eligibility & review queue</a><a href="#october-method">October methodology</a><a href="#organization/shea-stadiums">August archive</a></div>`;
    const notice=`<div class="notice"><b>October working edition · Non-debuted prospects only.</b> ${edition.summary.rankedPlayers} prospects ranked from verified publication inputs. ${edition.summary.eligibleAwaitingResearch} additional eligible players remain in the <a href="#october-review"><u>research queue</u></a>. This is a DD-led consensus, not a finished independent scouting reassessment.</div>`;
    if(page==='october-method') {
      app.innerHTML=`${nav}<article class="report"><span class="eyebrow">OCTOBER 6 / EDITORIAL METHODS</span><h1>DD leads. Evidence refines.</h1>${notice}<h2>Eligibility before ranking</h2><p>Any recorded MLB debut excludes a player, even if he remains rookie eligible. All ${edition.summary.rosterPlayersAudited} rostered players were inspected, including active, reserve, IL and minors slots. A zero season stat line does not undo an earlier debut. Official player records and career statistics were checked by MLBAM ID; the service tracker supplies a supplementary eligibility check.</p><h2>A bounded consensus</h2><p>Dynasty Dugout sets the baseline at 60%. Pitcher List contributes 15%, FanGraphs 10%, Just Baseball 10%, and Baseball America 5%. Supporting ranks adjust DD in logarithmic rank space. Each source’s difference is capped at a twofold ratio, which prevents one outlier from overwhelming DD. Missing supporting ranks are neutral and their weights are never redistributed.</p><code class="formula">${esc(edition.methodology.formula)}</code><p>A missing DD rank uses 501 as a censored boundary only when another verified rank exists. It is not an asserted DD #501. Players absent from every verified input stay unranked in the research queue. This model is an editorial starting point; it does not replace scouting evaluation.</p><h2>Coverage and dates matter</h2>${edition.sources.map(s=>`<div class="sourceitem"><b>${esc(s.name)}</b> · ${esc(s.date??s.retrievedDate)}${s.weight!=null?` · ${s.weight*100}%`:''}<p>${esc(s.context)}</p>${s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer"><u>Open source ↗</u></a>`:''}</div>`).join('')}<h2>History and movement</h2><p>August is preserved unchanged. October uses the October 6 Fantrax ownership snapshot, including Yoho’s confirmed identity as the former Friedl organization. Arrows compare organization ranks only when the player remains in the same organization. Changed eligibility rules, source coverage, the model and other players’ graduation also cause movement; arrows do not measure pure talent improvement.</p><h2>What remains unfinished</h2><p>The research queue requires current scouting and deeper ranking evidence. BA access was limited to its publicly indexed first 36 ranks. Farm rankings, grades, detailed scouting reports and unsourced metrics are not assigned here.</p></article>`;
      return;
    }
    if(page==='october-player') {
      const p=[...edition.rankings,...edition.reviewQueue].find(p=>p.playerId===id);
      if(!p){app.innerHTML=`${nav}<h1>Prospect not found</h1>`;return;}
      const old=p.historyPlayerId?archive.rankings.find(r=>r.playerId===p.historyPlayerId):null;
      app.innerHTML=`${nav}<a href="#october-org/${p.organizationId}">← ${esc(p.organization)}</a><span class="eyebrow blockeyebrow">OCTOBER WORKING PROFILE / NON-DEBUTED</span><h1>${esc(p.name)}</h1><p class="muted">${esc(p.rankingPosition)} · ${esc(p.mlbOrg)} · ${esc(p.organization)}</p><div class="profile"><section class="panel"><div class="facts"><div><span>LEAGUE RANK</span><b>${p.leagueRank?`#${p.leagueRank}`:'In review'}</b></div><div><span>ORG RANK</span><b>${p.organizationRank?`#${p.organizationRank}`:'Unranked'}</b></div><div><span>AGE / OCT 6</span><b>${p.age??'Unavailable'}</b></div><div><span>ROSTER SLOT</span><b>${esc(p.status.replaceAll('_',' '))}</b></div>${p.eta?`<div><span>ETA / SOURCE</span><b>${esc(p.eta)}</b></div>`:''}${p.ddTier?`<div><span>DD TIER</span><b>${p.ddTier}</b></div>`:''}</div><h2>Evaluation context</h2><p>${esc(p.rankingNote??'Eligible candidate with no rank in the currently verified publication inputs. Additional scouting research is required before assigning a rank.')}</p><p class="muted">A detailed original scouting report is pending. Missing performance metrics stay missing.</p><h2>Ranking history</h2>${old?`<p>August 2026 · ${esc(organizations.find(o=>o.id===old.organizationId)?.name)} #${old.organizationRank} · League #${old.leagueRank}</p>`:'<p>No safely matched August ranking available.</p>'}<p>October 2026 · ${esc(p.organization)} ${p.organizationRank?`#${p.organizationRank} · League #${p.leagueRank}`:'Research queue'}</p><p class="muted">Edition ranks use different eligibility rules and models.</p></section><aside class="panel"><h2>Publication inputs</h2>${Object.entries(p.sourceRanks).filter(([,r])=>r!=null).map(([s,r])=>`<p>${sourceLabel[s]} <b>#${r}</b></p>`).join('')||'<p>No current verified rank input.</p>'}<a href="#october-method"><u>Dates, weights and source limits →</u></a><h3>Identity & eligibility</h3><p>Fantrax ${esc(p.fantraxId)}<br>MLBAM ${p.mlbamId}<br>No recorded MLB debut as of October 6.</p>${p.bats&&p.throws?`<p>Bats / throws: ${esc(p.bats)} / ${esc(p.throws)}</p>`:''}${p.height&&p.weight?`<p>${esc(p.height)} · ${p.weight} lb</p>`:''}${p.draftYear?`<p>Draft year: ${p.draftYear}</p>`:''}<a href="https://www.milb.com/player/${p.mlbamId}" target="_blank" rel="noopener noreferrer"><u>Official player record ↗</u></a></aside></div>`;
      return;
    }
    if(page==='october-review') {
      app.innerHTML=`${nav}<span class="eyebrow">EVERY SLOT AUDITED</span><h1>The October eligibility audit</h1><div class="stats"><div><b>${edition.summary.rosterPlayersAudited}</b><span>ROSTER PLAYERS CHECKED</span></div><div><b>${edition.summary.eligiblePlayers}</b><span>NON-DEBUTED CANDIDATES</span></div><div><b>${edition.summary.debutedOrIneligibleExcluded}</b><span>EXCLUDED</span></div></div>${notice}<h2>Eligible, awaiting deeper research</h2><p class="muted">These players are accounted for, but not assigned arbitrary ranks to fill an organization’s Top 30.</p><div class="tablewrap"><table><thead><tr><th>PLAYER</th><th>ORGANIZATION</th><th>MLB</th><th>SLOT</th></tr></thead><tbody>${edition.reviewQueue.map(p=>`<tr><td><a href="${link(p)}">${esc(p.name)}</a></td><td>${esc(p.organization)}</td><td>${esc(p.mlbOrg)}</td><td>${esc(p.status)}</td></tr>`).join('')}</tbody></table></div><h2>Excluded players in ranking-source or minors slots</h2><p class="muted">All ${edition.excluded.length} exclusions are retained in the structured edition. This focused list shows players who might otherwise be mistaken for eligible candidates.</p><div class="tablewrap"><table><thead><tr><th>PLAYER</th><th>ORGANIZATION</th><th>SLOT</th><th>REASON</th></tr></thead><tbody>${edition.excluded.filter(p=>p.ddRank||p.status==='MINORS').map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(orgName(p.organizationId))}</td><td>${esc(p.status)}</td><td>${esc(p.reason)}</td></tr>`).join('')}</tbody></table></div>`;
      return;
    }
    const org=page==='october-org'?organizations.find(o=>o.id===id):null;
    if(page==='october-org'&&!org){app.innerHTML=`${nav}<h1>Organization not found</h1>`;return;}
    const pool=edition.rankings.filter(p=>!org||p.organizationId===id);
    const pending=edition.reviewQueue.filter(p=>!org||p.organizationId===id).length;
    app.innerHTML=`${nav}<span class="eyebrow">BANGALANGIN PIPELINE / OCTOBER 2026</span><h1>${esc(org?orgName(id):'League Top 100')}</h1><p class="muted">${org?`Organization pipeline · ${pool.length} ranked prospects · ${pending} in review`:'DD-led dynasty rankings across all 12 organizations'} · Non-debuted only</p>${notice}<div class="controls rankingcontrols"><input id="oct-search" aria-label="Search October prospects" placeholder="Search prospects…"><select id="oct-org" aria-label="Fantasy organization"><option value="">All 12 organizations</option>${organizations.map(o=>`<option value="${o.id}"${id===o.id?' selected':''}>${esc(orgName(o.id))}</option>`).join('')}</select><select id="oct-type" aria-label="Prospect type"><option value="">Hitters + pitchers</option><option value="H">Hitters</option><option value="P">Pitchers</option><option value="B">Two-way</option></select><select id="oct-scope" aria-label="Ranking scope">${org?'<option value="30">Org Top 30</option>':'<option value="100">League Top 100</option>'}<option value="all">All ranked prospects</option></select><select id="oct-sort" aria-label="Sort prospects"><option value="rank">Rank</option><option value="name">Name</option><option value="age">Age</option></select></div><p id="oct-count" class="muted" aria-live="polite"></p><div class="tablewrap"><table><thead><tr><th>${org?'ORG':'LEAGUE'}</th><th>PROSPECT</th><th>FANTASY ORGANIZATION</th><th>MLB</th><th>AGE</th><th>DD TIER</th><th>AUG ORG</th><th>MOVE*</th></tr></thead><tbody id="oct-rows"></tbody></table></div><p class="muted">*Movement is comparable only within the same organization; changed eligibility and methodology also change ranks. DD tiers retain DD’s labels. Unavailable tiers are omitted. <a href="#october-method"><u>Read the methodology →</u></a></p><div class="sectionhead"><h2>Browse all twelve farms</h2></div><div class="grid">${organizations.map(o=>`<a class="card" href="#october-org/${o.id}"><span class="badge">OCTOBER WORKING EDITION</span><h3>${esc(orgName(o.id))}</h3><p>${edition.rankings.filter(p=>p.organizationId===o.id).length} ranked · ${edition.reviewQueue.filter(p=>p.organizationId===o.id).length} in research →</p></a>`).join('')}</div>`;
    const el=key=>app.querySelector(`#oct-${key}`);
    const render=()=>{
      let rows=pool.filter(p=>(!el('org').value||p.organizationId===el('org').value)&&(!el('type').value||p.type===el('type').value)&&p.name.toLowerCase().includes(el('search').value.trim().toLowerCase()));
      if(el('scope').value!=='all')rows=rows.filter(p=>(org?p.organizationRank:p.leagueRank)<=Number(el('scope').value));
      rows.sort((a,b)=>el('sort').value==='name'?a.name.localeCompare(b.name):el('sort').value==='age'?(a.age??Infinity)-(b.age??Infinity):a.leagueRank-b.leagueRank);
      el('count').textContent=`${rows.length} prospects shown`;
      el('rows').innerHTML=rows.map(p=>`<tr><td>${org?p.organizationRank:p.leagueRank}</td><td><a href="${link(p)}">${esc(p.name)}</a><small>${esc(p.rankingPosition)} · ${esc(p.confidence)}</small></td><td><a href="#october-org/${p.organizationId}">${esc(p.organization)}</a></td><td>${esc(p.mlbOrg)}</td><td>${p.age??'—'}</td><td>${p.ddTier??'—'}</td><td>${p.previousOrganizationRank?`#${p.previousOrganizationRank}${p.previousOrganizationId!==p.organizationId?' (prior team)':''}`:'—'}</td><td>${movement(p)}</td></tr>`).join('')||'<tr><td colspan="8">No prospects match these filters.</td></tr>';
    };
    el('org').onchange=()=>{if(org&&el('org').value!==id)location.hash=el('org').value?`october-org/${el('org').value}`:'october';else render()};
    for(const key of ['search','type','scope','sort'])el(key).addEventListener(key==='search'?'input':'change',render);
    render();
  } catch(e) {if(location.hash.slice(1).split('/')[0]===page)app.innerHTML='<h1>October edition unavailable</h1><p>Reload to retry loading the edition.</p><a href="#home">Return home</a>'}
}
