const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let snapshot;
export async function showRosters(app){
 app.innerHTML='<p>Loading current rosters…</p>';
 try{if(!snapshot){const r=await fetch('data/ownership-snapshots/2026-10-06.json');if(!r.ok)throw Error('Roster unavailable');snapshot=await r.json()}
 if(location.hash!=='#rosters')return;
 app.innerHTML=`<span class="eyebrow">OCTOBER 6, 2026 / OWNERSHIP SNAPSHOT</span><h1>The current rosters</h1><p class="muted">12 organizations · 827 players · Fantrax period ${snapshot.period}</p><div class="notice">Complete league rosters, including major leaguers. Roster status is not prospect eligibility. This snapshot updates ownership; August rankings remain historical. October prospect evaluations are in progress.</div><div class="controls"><input id="roster-search" aria-label="Search all current players" placeholder="Search 827 rostered players…"><select id="roster-team" aria-label="Fantasy organization"><option value="">All 12 organizations</option>${snapshot.teams.map(t=>`<option value="${esc(t.fantraxTeamId)}">${esc(t.name)}</option>`).join('')}</select><select id="roster-status" aria-label="Roster status"><option value="">All roster statuses</option>${['ACTIVE','RESERVE','MINORS','INJURED_RESERVE'].map(s=>`<option>${s}</option>`).join('')}</select></div><p class="muted" id="roster-count" aria-live="polite"></p><div class="tablewrap"><table><thead><tr><th>PLAYER</th><th>FANTASY ORGANIZATION</th><th>MLB</th><th>POSITION</th><th>STATUS</th></tr></thead><tbody id="roster-rows"></tbody></table></div><p class="muted">Source: user-supplied Fantrax responses captured October 6. The response does not include an export timestamp. Eight archived names require identity review. Yoho and a Bottle of Rum was formerly Friedl on the Needle; organization identity is preserved across the rename.</p>`;
 const render=()=>{const q=document.querySelector('#roster-search').value.toLowerCase(),tid=document.querySelector('#roster-team').value,status=document.querySelector('#roster-status').value;const rows=snapshot.teams.filter(t=>!tid||t.fantraxTeamId===tid).flatMap(t=>t.players.map(p=>({...p,teamName:t.name}))).filter(p=>p.name.toLowerCase().includes(q)&&(!status||p.status===status)).sort((a,b)=>a.name.localeCompare(b.name));document.querySelector('#roster-count').textContent=`${rows.length} players shown`;document.querySelector('#roster-rows').innerHTML=rows.map(p=>`<tr><td style="font-size:14px">${esc(p.name)}<small>ID ${esc(p.fantraxId)}</small></td><td>${esc(p.teamName)}</td><td>${esc(p.mlbOrg)}</td><td>${esc(p.position)}</td><td>${esc(p.status.replaceAll('_',' '))}</td></tr>`).join('')||'<tr><td colspan="5">No players match these filters.</td></tr>'};for(const id of ['roster-search','roster-team','roster-status'])document.getElementById(id).addEventListener('input',render);render();
 }catch(e){if(location.hash==='#rosters')app.innerHTML='<h1>Rosters unavailable</h1><p>Please refresh to retry.</p>'}
}
