"""Build the assessment from frozen experiment outputs, without tuning."""
from pathlib import Path
import json,gzip,csv,hashlib,ast
import numpy as np
from collections import Counter
HERE=Path(__file__).resolve().parent
def read(name):
    p=HERE/name
    return list(csv.DictReader(p.open())) if name.endswith('.csv') else json.loads(gzip.decompress(p.read_bytes()) if name.endswith('.gz') else p.read_text())
def mdtable(headers,rows):return '\n'.join(['|'+'|'.join(headers)+'|','|'+'|'.join(['---']*len(headers))+'|']+['|'+'|'.join(str(v) for v in row)+'|' for row in rows])+'\n'
def fmt(v):return f'{float(v):.2f}' if v not in [None,''] else 'unknown'
cases=read('Chronological_Cases.json.gz');validation=read('Chronological_Validation.csv');cal=read('Probability_Calibration.csv');league=read('League_1900_Comparison.csv');named=[a for a in read('Diagnostic_12_Comparisons.csv') if a['candidate']=='fitted'];summary=read('Population_Component_Attribution.csv');gates=read('Release_Gates.json');coverage=read('Training_Coverage.json')
paired=[]
for fam in ['H','P']:
    xs=[a for a in cases if (a['role']=='H')==(fam=='H')]
    for method in ['repair','expected_structural','expected_fitted']:
        by={}
        for a in xs:by.setdefault(a['mlbam_id'],[]).append(abs(a[method]-a['actual'])-abs(a['frozen_hybrid']-a['actual']))
        groups=list(by.values());sums=np.array([sum(g) for g in groups]);sizes=np.array([len(g) for g in groups]);rng=np.random.default_rng(2718);ix=rng.integers(0,len(groups),(1500,len(groups)));ci=np.quantile(sums[ix].sum(1)/sizes[ix].sum(1),[.025,.975]);paired.append({'family':fam,'method':method,'player_clusters':len(groups),'delta_MAE_vs_frozen':float(sums.sum()/sizes.sum()),'paired95_low':float(ci[0]),'paired95_high':float(ci[1]),'status':'descriptive exposed evidence; not independent confirmation'})
with (HERE/'Paired_Comparisons.csv').open('w',newline='') as f:w=csv.DictWriter(f,list(paired[0]));w.writeheader();w.writerows(paired)

lines=['# Full-role versus expected-season workload: bounded research test\n\n',
'**The separation improves interpretation, but neither expected-season candidate beats the preserved strong benchmark overall. No candidate is selected or approved for numerical release. Production and dynasty calculations are unchanged.**\n\n',
'Continues research checkpoint `7b8ab45fdd4809881245543398672215f237f300`. Definitions and candidates were committed before candidate scoring (`31bc3af` local protocol commit). All scored 2026 waves are exposed; no genuinely untouched sample was established in the preserved data. Results below are exploratory chronological replays, not fresh holdout results. No parameters were changed after examining candidate errors. Output adapter defects were corrected without changing the scored workload estimators.\n\n',
'## What is, and is not, a full-role estimate\n\n',
'True full availability means eligibility on every scheduled season date, with the specified role retained throughout. Annual PA/IP/GP/GS cannot certify that condition. No preserved complete daily injury/active-roster history establishes it. Therefore the transparent full-role scheduling estimate is a **hypothetical role scenario**, and the historically fitted alternative is explicitly a **high-usage role-retention proxy**, not a medically verified full-availability forecast. The proxy is never trained on all partly active seasons and then relabeled healthy. Its eligible seasons meet the frozen count and role conditions; those conditions still cannot prove clinical health.\n\n',
'Role slots are 155 GP everyday, 115 GP platoon, 80 GP bench, 32 GS starter, 65 relief appearances, or 12 GS + 30 relief appearances swingman. These describe role scheduling while available, including ordinary rest/rotation spacing; they are not playing-time floors. Latest positive verified usage determines the scenario from forecast-date evidence only. Hitter PA/GP identifies everyday (>=3.8), platoon (>=2.8), or bench; missing GP is unknown, with a clearly flagged PA-only everyday proxy at >=400 PA. Pitcher start share >=.8 is starter, <=.1 reliever, otherwise swingman. A verified-zero latest season can inform expected risk while a prior positive role supplies the hypothetical retained-role scenario.\n\n',
'Fitted proxy eligibility: same forecast/observed annual role, GP>=145 everyday / >=100 platoon / >=70 bench; >=30 starts for starters; >=60 relief appearances for relievers; >=40 total appearances for swingmen. Pandemic 2020 targets are excluded. Missing GP cannot qualify. At least60 core training rows per role are required; otherwise the transparent scenario is used. Bench and swingman fits lack sufficient support even at the final vintage. Hitter GP coverage is current-catalog selected and is not a random historical census; proxy results must not be generalized to all players. No full-season MLB arrival scenario is substituted for a prospect forecast. All646 unsupported/prospect/two-way paths remain unchanged, with a separate fallback inventory.\n\n',
'## Exact calculation and risk accounting\n\n',
'For role scenario appearances A and frozen as-of appearance depth d, C = A*d (pitchers: C = GS*d_SP + RA*d_RP). Full-role counts use the role template or a squared-error count fit restricted to eligible proxy outcomes. Depth uses existing status-aware 3:2:1 usage smoothing; no talent engine is refit. Counting-stat rates are copied from production; QA3 yields are restored from the completed prior replay that implements the league rule (>=5 IP and <=2 ER, OR >=6 IP and <=3 ER).\n\n',
'The mutually exclusive joint outcomes s are absent, retained/high-usage, retained/reduced-usage, changed role, and unknown role. For each nonzero state the fitted squared-error ratio r_s estimates E(actual workload / scenario C | state, forecast inputs). Count-normalized fitting weights are proportional to C^2; all blended/displayed statistical targets are means. W = C * sum_{s!=absent} p_s*r_s. Participation q = 1-p_absent; conditional-active workload W/q is a derived display, not another model discount. The absence term is exactly -p_absent*C; each other term is p_s*C*(r_s-1). Their sum plus C reproduces W to numerical precision. Changed roles may exceed the specified role scenario; only absolute PA/IP bounds apply.\n\n',
'This is a joint-outcome model, not independently identified medical and demotion hazards. A reduced same-role season can reflect injury, time in the minors, roster competition, or other causes; the annual data cannot assign causation. **The retained/reduced contribution must not be called an injury adjustment.** Unknown outcomes remain separate, not silently assigned to an injured or bench state. Historical missed time in predictor features does not by itself prove a double multiplier: absence and active-shortened outcomes are disjoint targets here.\n\n',
'The current counting-stat adapter uses scenario q once and normalizes the preserved rate-role composition within active outcomes. Hitter active opportunity is represented without a400-PA conditional floor. Pitcher count feasibility (36 GS,85 appearances) is attributed separately before roster allocation. This adapter is a sensitivity, not evidence that its reductions improve accuracy. The independent role composition remains inherited; no new destination-specific role-transition superiority is claimed.\n\n',
'For team channel b, scale = min(1, verified team budget_b / sum expected demand_b). Apply it to compatible unconditional expected quantities only, never sum all hypothetical healthy capacities. Current40-man membership continuing into2027 is an assumption. Historical current rosters are not backfilled. Dated medical facts without a quantified forecast-year return window have zero numeric adjustment. The retained Berrios calendar-window envelope clips conditional starts; it is a timetable assumption, not an independent second medical probability. Independence from interruption risk is not clinically validated. With/without-allocator and medical-envelope columns are supplied; neither mechanism is accepted just because it lowers team totals.\n\n',
'## Historical results\n\n',
f'{len(cases)} eligible player-season forecasts, including{sum(a["actual"]==0 for a in cases)} observed zero-workload outcomes. Legacy matched populations plus the last2026 wave are replayed; earlier scored waves remain preserved context, not a fresh selection set. Core IDs mod5 1/2/3 fit models, ID4 calibrates probabilities, and target years never exceed min(forecast anchor,2025). The2026 target is never used in fitting. Cases cover annual incumbents; pre-MLB arrival forecasts are outside this count-validation population.\n\n']
metrics=[r for r in validation if r['window']=='all_exposed' and r['group']=='all' and r['evaluation']=='expected_all']
lines += [mdtable(['Family','Model','n','MAE','RMSE','Bias'],[[r['family'],r['method'],r['n'],fmt(r['MAE']),fmt(r['RMSE']),fmt(r['bias'])] for r in metrics]),'\nThe candidates reduce prior-repair bias, but lose MAE and RMSE to the frozen hybrid. Paired player-cluster intervals in Paired_Comparisons.csv describe exposed evidence only. Neither a selected name receiving more workload nor agreement with production constitutes historical accuracy.\n\n']
proxy=[r for r in validation if r['window']=='all_exposed' and r['group']=='all' and r['evaluation']=='conditional_high_usage_proxy']
lines += [mdtable(['Conditional proxy population','Model','n','MAE','RMSE','Bias'],[[r['family'],r['method'],r['n'],fmt(r['MAE']),fmt(r['RMSE']),fmt(r['bias'])] for r in proxy]),'\nThe fitted proxy does not improve conditional errors over the transparent scenario overall. This is selection-conditioned usage evaluation, not validation among medically verified fully available players. In total481 outcomes meet the proxy; sparse role cells, unknown hitter GP, and survivor-selected GP coverage limit conclusions.\n\n']
calrows=[r for r in cal if r['window']=='all_exposed' and r['group'] in ['all','established','young','interrupted','aging33plus','uncertain_role']]
lines += [mdtable(['Family','Cohort','n','Predicted participation','Observed','Brier','Prior Brier','Active workload bias'],[[r['family'],r['group'],r['n'],fmt(r['predicted_participation']),fmt(r['observed_participation']),fmt(r['Brier']),fmt(r['prior_Brier']),fmt(r['conditional_active_bias'])] for r in calrows]),'\nRole-retention Brier scores and five-state calibration bins are saved separately. Unknown future roles are excluded from known-role calibration but remain in unconditional workload validation. Workload deciles are formed from forecast-date workloads, not outcomes. All protected cohorts, per-anchor paired stability rules, and the original high-RBI bias gate retain their thresholds.\n\n']
failed=[g for g in gates['gates'] if not g['pass']]
lines += [mdtable(['Candidate','Failed gate','Value','Existing limit'],[[g.get('method','both'),g['gate'],fmt(g.get('value')),fmt(g.get('limit'))] for g in failed]),'\nA missing untouched holdout, historical daily health/role coverage, and historical allocator accuracy evidence also block release. No gate is relaxed or redefined to rescue a candidate. Preserved_Release_Gates.json retains the previous complete gate record.\n\n## Current population attribution\n\n']
pop=[r for r in summary if r['candidate']=='fitted']
columns=['full_role_PA_IP','absence_adjustment','retained_reduced_adjustment','changed_role_adjustment','high_usage_adjustment','unknown_role_adjustment','count_feasibility_adjustment','team_allocation_adjustment','medical_envelope_adjustment','final_expected']
lines += [mdtable(['Group','n']+columns,[[r['role'],r['n']]+[fmt(r[k]) for k in columns] for r in pop]),'\nThese are arithmetic contributions in a declared order, not causal injury effects. The league CSV also supplies raw expected workload, production, frozen hybrid, previous repair, and exact reconciliation residuals. Roster and medical scenarios are not included in the historical accuracy estimates because adequate dated historical evidence is absent.\n\n## Diagnostic illustrations (not tuning targets)\n\n',mdtable(['Player','Full-role proxy/scenario','Conditional active','Participation','Raw expected','Allocator','Final sensitivity','Previous repair'],[[r['name'],fmt(r['full_role_PA_IP']),fmt(r['conditional_given_MLB_participation']),fmt(r['participation_probability']),fmt(r['raw_expected_before_count_adapter']),fmt(r['team_allocation_adjustment']),fmt(r['final_expected']),fmt(r['previous_targeted_repair'])] for r in named]),'\n']
for name in ['Paul Skenes','Aaron Judge']:
    r=next(a for a in named if a['name']==name)
    lines.append(f'**{name}:** full-role {fmt(r["full_role_PA_IP"])} -> conditional active {fmt(r["conditional_given_MLB_participation"])} -> raw unconditional {fmt(r["raw_expected_before_count_adapter"])} -> count adapter {fmt(r["count_feasibility_adjustment"])} -> roster {fmt(r["team_allocation_adjustment"])} -> medical {fmt(r["medical_envelope_adjustment"])} -> final sensitivity {fmt(r["final_expected"])}. Latest verified usage is {fmt(r["latest_verified_workload"])} PA/IP, {fmt(r["latest_GP"])} GP, {fmt(r["latest_GS"])} GS. The healthy-role scenario is hypothetical and is not the realistic expected-season forecast.\n\n')
lines += ['Skenes retaining a full rotation scenario does not establish that all future active seasons have32 starts. The old25.7 conditional count and the new lower active expectation are forecasts across active shortened/changed-role seasons, not estimates of healthy full-role capacity. Judge is still classified as an everyday role scenario despite the verified shortened latest season; his expected forecast remains lower because the interruption/state model forecasts a mixture of outcomes. No player-specific floor or forced upward forecast appears in the implementation. The generic candidates fail protected gates; these named outputs cannot justify acceptance.\n\n',
'## What earned a place, what failed, what remains unresolved\n\n',
'- **Earned as research/reporting structure:** separate role scenario and unconditional expectation, preserved observation status, explicit joint-risk attribution, exactly one absence mixture, and transparent role fallbacks. They expose why an active expectation can be much lower than full-role capacity. This does not establish numerical superiority.\n',
'- **Failed as replacement estimates:** both new expected candidates lose overall MAE/RMSE against the strong benchmark and fail protected gates. Fitted full-role proxies add fitting complexity without improving overall proxy errors. Retain the benchmark; do not promote either candidate.\n',
'- **Not validated:** team-budget allocation, medical-window independence, daily role retention, true full-health scenarios, and realistic arrival probability for unsupported prospects. The team allocator changes current outputs but has no matched historical accuracy test. A fresh future vintage or genuinely untouched outcome sample is needed before selecting further numerical repairs.\n',
'- **Confirmed output defects corrected:** a naive scale-only count adapter exceeded36 starts (maximum43.4237), and the pre-roster template omitted completed QA3 yields. Fixed bounds and restored frozen QA3 yields are separate from opportunity-model tuning; their contributions remain auditable.\n\n',
'No new talent model, prospect translations, eight-year paths, dynasty value, replacement accessibility or Trade Analyzer logic is changed.\n\n## Reproduction and executable references\n\n',
'Restore the three preserved checkpoint archives (first-year-repair/restore_checkpoint.py, roster-opportunity/restore_checkpoint.py, targeted-repair/restore.py), then run:\n\n```bash\nPYTHONDONTWRITEBYTECODE=1 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 "$CODEX_PRIMARY_RUNTIME_PYTHON" docs/model-audit/workload-correction/architecture-investigation/joint-opportunity/full-workload-scenario/run.py /absolute/recovered/model /absolute/recovered/beta-unpacked.json\nPYTHONDONTWRITEBYTECODE=1 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 "$CODEX_PRIMARY_RUNTIME_PYTHON" docs/model-audit/workload-correction/architecture-investigation/joint-opportunity/full-workload-scenario/test_contracts.py /absolute/recovered/model /absolute/recovered/beta-unpacked.json\n"$CODEX_PRIMARY_RUNTIME_PYTHON" docs/model-audit/workload-correction/architecture-investigation/joint-opportunity/full-workload-scenario/summarize.py\n```\n\n']
refs=[]
for p in [HERE/'run.py',HERE.parent/'targeted-repair/engine.py']:
    for node in ast.parse(p.read_text()).body:
        if isinstance(node,(ast.FunctionDef,ast.ClassDef)) and node.name in ['observation','evidence_features','fz','fit_model','predict_model','allocate_verified','apply_verified_availability','forecast_role','target_label','inputs','depths','fit','predict','component_for','current']:
            refs.append([str(p.relative_to(HERE.parent)),node.name,node.lineno])
lines += [mdtable(['Source','Function','Line'],refs),'\nThe CSVs, compressed player components, fitted joblib artifacts, protocol, manifests, calibration bins and gate outputs constitute the reproducible checkpoint.\n']
(HERE/'Scenario_Report.md').write_text(''.join(lines))
(HERE/'Implementation_Freeze.json').write_text(json.dumps({'protocol_sha256':hashlib.sha256((HERE/'Protocol_Freeze.json').read_bytes()).hexdigest(),'source_sha256':hashlib.sha256((HERE/'run.py').read_bytes()).hexdigest(),'candidate_selection_performed':False,'post_score_parameter_tuning':False,'post_score_engineering':'Output adapter count feasibility and omitted QA3 yield corrections only; no scoring-model change','evaluation':'exploratory exposed','baseline_checkpoint':'7b8ab45fdd4809881245543398672215f237f300'},indent=2)+'\n')
print('Report saved; numerical release remains blocked')
