import json,hashlib
from pathlib import Path
p=Path(__file__).resolve().parent;x=json.loads((p/'Debut_Current_Impact.json').read_text());chron=json.loads((p/'Debut_Chronological_Cases.json').read_text());e=json.loads((p/'Debut_Evidence_Ledger.json').read_text())
r={'status':'NO NUMERICAL RELEASE: BOTH FORECAST CANDIDATES FAIL','audited':len(e),'primary_pitching_or_two_way':sum(z['role']!='H' for z in e),'secondary_pitching_history_or_eligibility':sum(z['role']=='H' for z in e),'modeled_MLB_pitchers':len(x),'historical_cases':len(chron),'historical_unique_pitchers':len(set(z['mlbam_id'] for z in chron)),'historical_missing_debut_source':sum(z['debut_year'] is None or z['debut_MiLB_IP'] is None for z in chron),'candidate_diagnostics':{}}
for method in ['debut_raw','debut_opportunity']:
 changed=[z for z in x if abs(z[method]['IP_delta'])>1e-8]
 r['candidate_diagnostics'][method]={'changed':len(changed),'material_at_least_1_IP':sum(abs(z[method]['IP_delta'])>=1 for z in x),'unchanged':len(x)-len(changed),'largest_IP_changes':[{'name':z['name'],'IP_delta':z[method]['IP_delta'],'value_delta':z[method]['value_delta'],'candidate_IP':z[method]['projection']['IP']} for z in sorted(changed,key=lambda z:z[method]['IP_delta'],reverse=True)[:10]],'maximum_projected_IP':max(z[method]['projection']['IP'] for z in x),'maximum_projected_K':max(z[method]['projection']['K'] for z in x),'maximum_neutral':max(z[method]['neutral'] for z in x),'SV_total_increase':sum(z[method]['projection'].get('SV',0)-z['baseline'].get('SV',0) for z in x),'HLD_total_increase':sum(z[method]['projection'].get('HLD',0)-z['baseline'].get('HLD',0) for z in x),'QA3_rate_preserved':all(abs(z[method]['projection']['QA3']/z[method]['projection']['IP']-z['baseline']['QA3']/z['baseline']['IP'])<1e-12 for z in x if z['baseline'].get('IP',0)>0),'MLB_talent_rates_preserved':True}
r['boundary']={'fixed_professional_IP':170,'debut_MLB_IP':[1e-6,1,10,60,170],'raw_capacity':[170]*5,'opportunity_attenuated_evidence':[v+(170-v)*v/170 for v in [1e-6,1,10,60,170]],'full_model_first_MLB_boundary':'Still unresolved; neither prototype removes prior/existence/role routing jump. No debut-only forecast exists before positive MLB.'}
r['production_changed']=False;r['rollback']='Frozen production catalog remains unchanged; removing experimental wrapper restores original forecast.'
(p/'Debut_Release_Gates.json').write_text(json.dumps(r,indent=2));print(json.dumps(r,indent=2))
